"""init models

Revision ID: 770da2264dc0
Revises: 
Create Date: 2019-09-06 11:58:29.132997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770da2264dc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mogu_banner',
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('title', sa.String(length=80), nullable=True, comment='轮播标题'),
    sa.Column('link', sa.String(length=164), nullable=True, comment='广告链接'),
    sa.Column('image_url', sa.String(length=256), nullable=True, comment='图片路径'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mogu_goods_category',
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='分类名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mogu_nav',
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=80), nullable=True, comment='导航名称'),
    sa.Column('link', sa.String(length=164), nullable=True, comment='导航链接'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父导航ID'),
    sa.ForeignKeyConstraint(['parent_id'], ['mogu_nav.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mogu_news_category',
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='分类名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mogu_site_config',
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('title', sa.String(length=80), nullable=True, comment='提示文本'),
    sa.Column('name', sa.String(length=500), nullable=True, comment='变量名'),
    sa.Column('value', sa.String(length=500), nullable=True, comment='变量值'),
    sa.Column('dtype', sa.Enum('text', 'image', 'link', 'video'), nullable=True, comment='变量类型'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mogu_goods_spu',
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='商品标题'),
    sa.Column('is_recommend', sa.Boolean(), nullable=True, comment='是否推荐到首页'),
    sa.Column('descript', sa.String(length=512), nullable=False, comment='商品描述'),
    sa.Column('effect', sa.Text(), nullable=False, comment='产品效果'),
    sa.Column('image_url', sa.String(length=256), nullable=True, comment='封面图片'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.ForeignKeyConstraint(['category_id'], ['mogu_goods_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mogu_news',
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='文章标题'),
    sa.Column('descript', sa.String(length=512), nullable=False, comment='文章摘要'),
    sa.Column('content', sa.Text(), nullable=False, comment='文章内容'),
    sa.Column('read_count', sa.Integer(), nullable=True, comment='浏览量'),
    sa.Column('image_url', sa.String(length=256), nullable=True, comment='封面图片'),
    sa.Column('author', sa.String(length=64), nullable=True, comment='作者'),
    sa.Column('is_recommend', sa.Boolean(), nullable=True, comment='是否推荐到首页'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.ForeignKeyConstraint(['category_id'], ['mogu_news_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mogu_news')
    op.drop_table('mogu_goods_spu')
    op.drop_table('mogu_site_config')
    op.drop_table('mogu_news_category')
    op.drop_table('mogu_nav')
    op.drop_table('mogu_goods_category')
    op.drop_table('mogu_banner')
    # ### end Alembic commands ###
